# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_quote_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_quotes', to='portal.User'),
        ),
    ]
